security:
    encoders:
        App\Entity\Participant:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Participant
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            #Remember me
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 6048000 #10 semaines
                path: /

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    #ROLE_USER est défini par défaut pour tous les utilisateurs connectés donc pas besoin de le créer
    #Création du ROLE_ADMIN qui hérite de tous les pouvoirs du ROLE_USER
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    access_control:
        #On autorise n'importe qui à se connecter.
        #Il faut etre connecté pour naviguer sur les autres pages
        #Le formulaire 'register' n'est accessible que par le ROLE_ADMIN
        - {path: ^/login, roles:}
        - {path: ^/register, roles: ROLE_ADMIN}
        - {path: ^/archive, roles: ROLE_ADMIN}
        - { path: ^/, roles: ROLE_USER }
